// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyuzDeZ3pgWTAM6hrOPfMnsRNrxi1vITA',
    appId: '1:684586474296:web:3bb39cb7916f1b22ed3fcd',
    messagingSenderId: '684586474296',
    projectId: 'test-stg-87e23',
    authDomain: 'test-stg-87e23.firebaseapp.com',
    storageBucket: 'test-stg-87e23.appspot.com',
    measurementId: 'G-MWETD8N823',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO_-AZTFBFOqt0MiDbm-XYoOGiGWsx5U8',
    appId: '1:684586474296:android:005194211761deafed3fcd',
    messagingSenderId: '684586474296',
    projectId: 'test-stg-87e23',
    storageBucket: 'test-stg-87e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzFsoheYgFg7db0heaw5263DC6g6a6Vg',
    appId: '1:684586474296:ios:55808fd425057723ed3fcd',
    messagingSenderId: '684586474296',
    projectId: 'test-stg-87e23',
    storageBucket: 'test-stg-87e23.appspot.com',
    iosBundleId: 'com.example.verygoodcore.test-app.stg',
  );
}
