// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH9CA9EZu3RmwwmOklpUf9frQSOlIDU3E',
    appId: '1:911108598943:web:f1d5d28a1e7089095b06aa',
    messagingSenderId: '911108598943',
    projectId: 'test-prod-1b4e5',
    authDomain: 'test-prod-1b4e5.firebaseapp.com',
    storageBucket: 'test-prod-1b4e5.appspot.com',
    measurementId: 'G-1NR41SQVQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4T982fXZvSt1A0_OCWFmVYOcSB7ij9oI',
    appId: '1:911108598943:android:c8cfa11661f190b75b06aa',
    messagingSenderId: '911108598943',
    projectId: 'test-prod-1b4e5',
    storageBucket: 'test-prod-1b4e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyHWBJMrJDqPkoCM2tRCnNV7Be_jovVVw',
    appId: '1:911108598943:ios:362dc1061cf9ac1a5b06aa',
    messagingSenderId: '911108598943',
    projectId: 'test-prod-1b4e5',
    storageBucket: 'test-prod-1b4e5.appspot.com',
    iosBundleId: 'com.example.verygoodcore.test-app',
  );
}
